apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: jellyfin
spec:
  storageClassName: proxmox-csi
  volumeName: jellyfin-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
