apiVersion: v1
kind: Namespace
metadata:
  name: http-echo
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  annotations:
    external-dns.custom/type: private
  name: echo
  namespace: echo-server
spec:
  endpoints:
  - dnsName: echo.<path:stringreplacesecret#domain>
    providerSpecific:
    - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
      value: 'false'
    recordType: CNAME
    targets:
    - intgw.<path:stringreplacesecret#domain>
