apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflared
data:
  config.yaml: |
    originRequest:
      originServerName: cloudflared.<path:stringreplacesecret#domain>
    ingress:
      - service: https://cilium-gateway-external.gateway.svc.cluster.local:443