apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: cloudflared-pi
        property: credentials.json
    - secretKey: TunnelID
      remoteRef:
        key: cloudflared-pi
        property: TunnelID