---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCIZZ3RQWA6u5bOYry1tSc+meBW9m8n5fC/0jhmE0lbIZYX/tAwMZbT2G3bdyWqFs0d3GGZWUAx2swE1xdGRDYQ8u19XcLcLM6oQPiSvg7lY7/gsvoXa6cz2TQfLReqOJoPxXBfHbhFi2JogTFvNZFGaNCNnUyqRpHwvzyxqBu/91MRmocFxlRvjneReTDJFjvOoB1S4U12REu/mozdnT1qrNtP8JjdiyhzI5gSFDXsbEiwTFh89gRRktR1suiLMNEwiTEWHrbBxpSlqp03O80EnB4b0qF+4vUOhxJKWRt+7q/bFb6X5DNCimjFw1PjrxvvAZjSzsKnJ/qW11kwWd+EVBLZEQuu4lVgByGL7Hx4vVO2bC3Ijy60rGhYuCHltEIgK+YHESIF1F1WGF6XqvaGb78CZ6E15ay+OEVjHPz3oqHh5qrQpTDi3QqaNSXdYh/Bvp3kbJ/GNmv8TpLNZVFJYzQDvmzM8eQ5Bpi+Z7BEr3ZT1nraeEXrrzQgfPv5Z5lvPtX2OCOyrX7xVuCvHWBo4PbuZmuzuCfj1NcsvX0gHh665+hcyYnB5i9hLaAqajvpmLDNtGi4RZXYS4zocBZf5YKayuVIpJum3XE9+wx0vP1C+WzqI3FUvndJIACg98Oiv9dzvqqZ5nDa50Gd+yIqat7kcMMTMte7CpnsgLbkPDh3PB8nzZWbv2/4Kbr+p1IO9kL8ykkPpUv7SV8KE13SMD5N2VdqBZlm9xa4fZsO47vcagebdqAnA4UWk6GGs1xC3r3bOexVkBPpYjM9vPuyk+scBMeEg5r4hcY8f86WHuiF9JyLk/vg7D91DYPTUJG8kC8KXPRKwwuet7D6GNjzgBLch3C1Y59sZbe35RbQ+kdWPkW2xjEdmG3Kxm/ZyS3snApAhtLuYlUqDaUKeg4IG8dz1/0jVz7jhM4p4a0=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
