autoDirectNodeRoutes: true
bandwidthManager:
  bbr: false
  enabled: true
bpf:
  hostLegacyRouting: true
  masquerade: true
cluster:
  id: 1
  name: home-cluster
containerRuntime:
  integration: containerd
  socketPath: /var/run/k3s/containerd/containerd.sock
enableRuntimeDeviceDetection: true
endpointRoutes:
  enabled: true
gatewayAPI:
  enabled: true
  secretsNamespace:
    create: false
    name: certificate
hubble:
  enabled: true
  metrics:
    enabled:
    - dns:query
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    ingress:
      enabled: false
    rollOutPods: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sServiceHost: 192.168.100.176
k8sServicePort: 6443
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
l2announcements:
  enabled: true
loadBalancer:
  acceleration: best-effort
  dsrDispatch: opt
  l7:
    backend: envoy
  mode: dsr
localRedirectPolicy: true
rollOutCiliumPods: true
routingMode: native
securityContext:
  privileged: true
