adminUser: admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      uid: prometheus
      url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
    - access: proxy
      jsonData:
        maxLines: 250
      name: Loki
      type: loki
      uid: loki
      url: http://loki-gateway.observability.svc.cluster.local
    deleteDatasources:
    - name: Alertmanager
      orgId: 1
    - name: Loki
      orgId: 1
    - name: Prometheus
      orgId: 1
env:
  GF_AUTH_GENERIC_OAUTH_API_URL: https://auth.<path:stringreplacesecret#domain>/application/o/userinfo/
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://auth.<path:stringreplacesecret#domain>/application/o/authorize/
  GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: 'true'
  GF_AUTH_GENERIC_OAUTH_ENABLED: 'true'
  GF_AUTH_GENERIC_OAUTH_NAME: authentik
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: contains(groups[*], 'Grafana Admin')
    && 'Admin' || 'Viewer'
  GF_AUTH_GENERIC_OAUTH_SCOPES: openid profile email offline_access
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://auth.<path:stringreplacesecret#domain>/application/o/token/
  GF_SERVER_ROOT_URL: https://grafana.<path:stringreplacesecret#domain>
envValueFrom:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
    secretKeyRef:
      key: grafana_client_id
      name: sso
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
    secretKeyRef:
      key: grafana_client_secret
      name: sso
