addons:
  codeserver:
    enabled: true
    volumeMounts:
    - mountPath: /app/config
      name: config
env:
  TZ: America/New_York
image:
  repository: ghcr.io/gethomepage/homepage
  tag: v0.8.11
persistence:
  config:
    enabled: true
    mountPath: /app/config
    size: 1Gi
service:
  main:
    ports:
      http:
        port: 3000
