apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-secret.yaml

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    version: 1.15.0
    releaseName: 1passwordconnect
    namespace: 1passwordconnect
    valuesInline:
      connect:
        credentialsName: 1passwordconnect
        credentialsKey: 1password-credentials.json
        serviceType: ClusterIP

namespace: 1passwordconnect

