backend:
  replicas: 0
deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
    - from: 2024-04-20
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v13
      store: tsdb
  storage:
    type: filesystem
read:
  replicas: 0
singleBinary:
  replicas: 1
write:
  replicas: 0
