tunnel: gauss-k8s
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true

warp-routing:
  enabled: true

ingress:
  - hostname: hello.euclid.stonegarden.dev
    service: hello_world
  - hostname: proxmox.stonegarden.dev
    service: https://proxmox.proxmox.svc.cluster.local:443
    #service: https://cilium-gateway-tls-passthrough.gateway.svc.cluster.local:443
    originRequest:
      originServerName: proxmox.stonegarden.dev
  - hostname: truenas.stonegarden.dev
    service: https://192.168.1.55:443
    #service: https://truenas.truenas.svc.cluster.local:443
    #service: https://cilium-gateway-tls-passthrough.gateway.svc.cluster.local:443
    originRequest:
      originServerName: truenas.stonegarden.dev
  - hostname: "*.euclid.stonegarden.dev"
    service: https://cilium-gateway-euclid.gateway.svc.cluster.local:443
    originRequest:
      originServerName: "*.euclid.stonegarden.dev"
  - hostname: "*.stonegarden.dev"
    service: https://cilium-gateway-stonegarden.gateway.svc.cluster.local:443
    originRequest:
      originServerName: "*.stonegarden.dev"
  - hostname: stonegarden.dev
    service: https://cilium-gateway-stonegarden.gateway.svc.cluster.local:443
    originRequest:
      originServerName: stonegarden.dev
  - service: http_status:404
