tunnel: gauss-k8s
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true

warp-routing:
  enabled: true

ingress:
  - hostname: "hello.vanillax.xyz"
    service: hello_world
  - hostname: "https://libreddit.vanillax.xyz"
    service: libreddit
    originRequest:
      originServerName: "*.vanillax.xyz"
  - hostname: "ingress.vanillax.xyz"
    service: https://external-gateway.gateway.svc.cluster.local:443
    originRequest:
      originServerName: "*.vanillax.xyz"
  - hostname: "*.vanillax.xyz"
    service: https://external-gateway.gateway.svc.cluster.local:443
    originRequest:
      originServerName: "*.vanillax.xyz"
  - service: http_status:404
