---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCTxXw6aSqTyB+vY1boO9fmGMumi5KDzWKf+/nHri/NDMDLOEwfU2pEmv3ELIFBKWiYuMUXIsyjgSwKdYd4HeTVB9iuvG75b9Pn6XhL8SHc+/o73tFWrBOleIxmBDhlhjnAIgcqvSLwKEQc4xK/d/Mjp3WwJt4UoCZKF8pUHagQsrdBchoAQ0wmLWAAFDIkVtPcLdQtTsdIoUFynLBhz/SalB5kgenHFeJF5A5xC2Jekg1ZCH+s4tKbv8rjZsqWu8m9zsdGHYq2aolQGgKMJp2lynUQLXgx/jaSm/JtIPXs/HaJN0TqAiFeayrradN9oI8R33vGIpP3vu8rlhVLy6c4gpddc0WyyGbvI04fLn8mBR0c4QiRvhhFUjlBXkHzW8KKGKkmSfTLEyAepodhPUEI3DOmjev4BDrsaLqRoSyvmmfsea8KcDOXWJGll1/6jCUskuVj7QSQTyU3kNY3V+JrBQPpapKvIIhJBtWSLcntbLGX78LgCQ8+2k0pCcKsTVGzhQuNCLEiZS9q3AJeXuVTEqUUuILqfzl6VshQpS5g8XaGiyq+TBXxiDP7mt4V0Ny4KI8ON5/oVsn5fzuQRuajR907a1nmuSIOpR1l6oJWJ8OcjTCs+iQ37H5gL1oNMsrdXAO1NnURtuCLQwbyIff0UXT4twUhAdXvnkg+KA9Im2954lciPeQHRtNae/dS2EZIUIbN8ESkt5Z4TWlhYCEaiNgfCvN2RnHm7oBInPNDZ0uCLqRUnwb27fyhUZT0xwHjCUM3XyUjOjdiH8Pr3oLHoH90ydIkvfqQW9FEbVIruMMk8Y+fS1GbCfm7HWHQ+O/yN4WdP5s9zR92F0yYN+2bGml62sGM0kAPkY9J6K1KxL1V7oCdZACBsim+zOa9Wnxyl4Bxcsk44xpUyKaI/tmjlx7OWJSww3EvW4lwwR3LfnFNW/ddig==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
