apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-class.yaml
  - ns.yaml
  - cloudflare-api-token.yaml
  - cloudflare-issuer.yaml
  - gw-euclid.yaml
  - gw-stonegarden.yaml
  - gw-tls-passthrough.yaml
