apiVersion: v1
kind: Namespace
metadata:
  name: certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-production
  namespace: certificate
spec:
  commonName: <path:stringreplacesecret#domain>
  dnsNames:
  - <path:stringreplacesecret#domain>
  - '*.<path:stringreplacesecret#domain>'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: wildcard-production
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allowfromns-gateway
  namespace: certificate
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: gateway
  to:
  - group: ''
    kind: Secret
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: wildcard-production
  namespace: certificate
spec:
  data:
  - match:
      remoteRef:
        property: tls.crt
        remoteKey: certificate.wildcard-production-proxmox
      secretKey: tls.crt
  - match:
      remoteRef:
        property: tls.key
        remoteKey: certificate.wildcard-production-proxmox
      secretKey: tls.key
  refreshInterval: 5m
  secretStoreRefs:
  - kind: ClusterSecretStore
    name: 1password
  selector:
    secret:
      name: wildcard-production
