---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: gateway
spec:
  encryptedData:
    api-token: AgC6hHedwvYDta07/uyowWQf2G6csKpX3JOm/FhwZHZiiwjDqo2CRvKhGWcXweyMOX3xIHQtvvvW7d0HC81HjE0IJI7mwnE+/SYzy3ltLCqqSphi2oGVQOjf2kDkx8YUpEn5IjuwZxmzZblSo0Eqfii93sh2aJXhtv9OxtvAUyN95wIRIzthNeQ/ZcsBvrdWY3A+Te6F5CdT/Ynknj66zFnWCMlkLZ4EkZDZUowKXy6klVzlCsVPCnEjBDhFStzRNVKZpTOE5r5i4MF5Z/tKhwTzdTv+eF3T9Y87AaehutkdONvA1LQh0HDALlZIrKKArCBpx6aR/3pGY9rcTqeZcm5tlWaHtZystGGhYyqw4K0X0bRDbQ5jh13mqnI7B1fpZ+PsvcUUDHhHc0BlzzD1pOh5EkoP5kpH383szzN+YsAKUO4H1uKxs666F+/mnoVIXKg0ktpevTZ1NwElj3HmC1hnPLBhyJzZQt60zBCeYChNd+5MXVYnTvQo96DxpmdBvL+YFyxqSqjKZP28bnzukkGaNkvQd6rrJOW3g8885uACa828gUFFTItMVbTesLRUHNzqa7750LVzNHbpTvSbQA/qPl2GhtrrJ6YDEOWkQz4wHS/8OCVTEy8LRZuoo469UcP/xk/3Fvs3oAm/8zdfjd1kym8hJhVqsWAOiK8aFH7wFVZ03emFwF9/2vceTqtevH5Ha/viuKIcS8gPX5vLz3pJLYyUvCuHnwmTSN8k57SaAOLAN8glNkn3
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: gateway
