apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
spec:
  sourceRepos:
    - 'https://gitlab.com/vehagn/mini-homelab*'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'csi-proxmox'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
