apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/mitchross/k3s-argocd-raspberrypi'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'cert-manager'
      server: '*'
    - namespace: 'node-feature-discovery'
      server: '*'
    - namespace: 'intel-device-plugins'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'external-secrets'
      server: '*'
    - namespace: '1passwordconnect'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
