apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: plex

configMapGenerator:
  - name: plex-env
    namespace: plex
    literals:
      - TZ="Europe/Oslo"
      - PLEX_ADVERTISE_URL=https://plex.stonegarden.dev:443,http://192.168.1.228:32400

resources:
  - ns.yaml
  - svc.yaml
  - pvc.yaml
  - ingress.yaml
  - deployment.yaml
