apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - external-secrets.yaml
  - cluster-secret-store.yaml
  - external-secrets-app.yaml

namespace: external-secrets