apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stringreplacesecret
  namespace: argocd
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: domain
      remoteRef:
        key: stringreplacesecret-pi
        property: domain
    - secretKey: cloudflaretunnelid
      remoteRef:
        key: stringreplacesecret-pi
        property: cloudflaretunnelid
    - secretKey: ciliumipamcidr
      remoteRef:
        key: stringreplacesecret-pi
        property: ciliumipamcidr