apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 6.0.6
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml

configMapGenerator:
  - name: argocd-cmp-cm
    behavior: merge
    literals:
      - |
        data:
          kustomize-build-with-helm.yaml: |
            apiVersion: argoproj.io/v1alpha1
            kind: ConfigManagementPlugin
            metadata:
              name: kustomize-build-with-helm
            spec:
              generate:
                command: ["sh", "-c"]
                args: ["kustomize build --enable-helm"]
          avp-directory-include.yaml: |
            apiVersion: argoproj.io/v1alpha1
            kind: ConfigManagementPlugin
            metadata:
              name: avp-directory-include
            spec:
              generate:
                command: [bash, -c]
                args: [argocd-vault-plugin generate $ARGOCD_ENV_FILE_NAME]