apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml
  - rbac.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 6.0.6
    releaseName: "argocd"
    namespace: argocd
    valuesFile: values.yaml

# configMapGenerator:
#   - name: argocd-cm
#     behavior: merge
#     literals:
#       - AVP_AUTH_TYPE=k8s
#       - AVP_K8S_ROLE=argocd
#       - AVP_K8S_MOUNT_PATH=/v1/auth/kubernetes
#       - AVP_TYPE=vault
#       - AVP_VAULT_ADDR=http://vault.vault.svc.cluster.local:8200