apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-vault-plugin
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-vault-plugin
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-vault-plugin
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-vault-plugin
roleRef:
  kind: Role
  name: argocd-vault-plugin
  apiGroup: rbac.authorization.k8s.io