configs:
  cm:
    application.resourceTrackingMethod: "annotation+label"
    url: "https://argocd.<path:stringreplacesecret#domain>"
    dex.config: |
      connectors:
        - type: oidc
          name: authentik
          id: authentik
          config:
            issuer: https://auth.<path:stringreplacesecret#domain>/application/o/argocd/
            clientID: $sso:client_id
            clientSecret: $sso:client_secret
            insecureEnableGroups: true
            scopes:
              - openid
              - profile
              - email
  cmp:
    create: true
  params:
    server.insecure: true

repoServer:
  extraContainers:
    - name: kustomize-build-with-helm
      command: [/var/run/argocd/argocd-cmp-server]
      image: '{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}'
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - name: plugins
          mountPath: /home/argocd/cmp-server/plugins
        - name: cmp-plugin
          mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: kustomize-build-with-helm.yaml
        - mountPath: /tmp
          name: cmp-tmp
    - name: plugin-avp-directory-include
      command: [/var/run/argocd/argocd-cmp-server]
      image: '{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}'
      env:
        - name: AVP_TYPE
          value: kubernetessecret
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: cmp-tmp
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin
        - name: cmp-plugin
          mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp-directory-include.yaml
  volumes:
    - name: cmp-plugin
      configMap:
        name: argocd-cmp-cm
    - name: cmp-tmp
      emptyDir: {}
    - name: custom-tools
      emptyDir: {}
  initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8:8.10-901.1716497712
      env:
        - name: AVP_VERSION
          value: 1.17.0
      command: [sh, -c]
      args:
        - >-
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/) -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools