---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCO1a9vLLbbmVU+ocoPEgwhQLzlWFf47f0SxxzdReW/4uYafxIbHOOoKAJMseqmL9B2mkrQd+6+b1xKE1LWn2pKY5mz6jNMiDZW6sjSEc91+3tP5EOcRfX3SJCKvtnbWat90yZhDQErDRe6E+H0nbj5h5el3sxM1d3xj5c0aLlrAVwYkbpeHQMdEcAlo4Fw0/f3OZpY13aNgBJxgqE4vwwTwnQSnGT3978zw6eHaGyy9BJmLNHDbnelrdLFkn/x/0zPOgrR5+2bOrvQHSNKESiLXbjECDgEtfzfQ2f/ICblD+rhcAmYqRWhR17+1H5N+SPSfW984KVCCUIyoEfxWwzD4KturWqZTMfaqHebgQkC6p907QGZC4lX0jiBKpzcAh/K7UnvqcN8WWdK2RLwTfojEbatoBK1aHD8e5x0pNyZ2M1Qlr8mvfIEciww1iDKdqAYecE5FN0WIrHwhB2/LLPN0CU+Nv/i5WO+fM6pMlN6t7/YjI0/1LjRC035RklK7fVUYe1V1uHUqdqEkc5c9Rn6zj4+yKp7tIxzYjDw6NjSC80PBvda2FX8A/cq2akT+V99b9er2BcNJNeTTUc9hFSxSRGA8ztrud0q36ceNUPpavEmB1MdIfM+abqDfTfA3h9Qt1EauuxzxQgIe9hKZ4BwAcE/i2f2zWvxK9PmB4x0DPAOBLXy0D44kmwW1GLnaFVZfXlGkTBH4YsmgAW1gxdyfXRRrT+IN+NZPD0vnxyx2+GouOnW46DM
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
