apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/mitchross/k3s-argocd-raspberrypi'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'haos'
      server: '*'
    - namespace: 'proxmox'
      server: '*'
    - namespace: 'truenas'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'