apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remark42
  namespace: blog
spec:
  storageClassName: proxmox-csi
  volumeName: pv-remark42
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
