apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - providers/keycloak
#  - https://doc.crds.dev/raw/github.com/crossplane/crossplane@v1.16.0 # renovate: helm=crossplane registry=https://charts.crossplane.io/stable
#  - https://doc.crds.dev/raw/github.com/crossplane-contrib/provider-keycloak@v1.6.0 # renovate: github-releases=crossplane-contrib/provider-keycloak

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    releaseName: crossplane
    namespace: crossplane
    version: 1.16.0
