apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-manifest
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/mitchross/k3s-argocd-raspberrypi.git
        revision: HEAD
        files:
          - path: manifest/*.yaml
  template:
    metadata:
      name: '{{ normalize .path.filename }}'
    spec:
      project: homelab
      source:
        repoURL: https://github.com/mitchross/k3s-argocd-raspberrypi.git
        path: '{{ .path.path }}'
        plugin:
          name: avp-directory-include
          env:
            - name: FILE_NAME
              value: '{{ .path.filename }}'
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: '{{ trimSuffix (ext ".yaml") (base .path.filename) }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
