apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: whoami

resources:
  - svc.yaml
  - deployment.yaml
#  - ingress.yaml
#  - ingress-shared.yaml
#  - ingress-dedicated.yaml
  - http-route.yaml
  - http-route-test.yaml