cluster:
  name: abel
  id: 1

k8sServiceHost: "192.168.1.100"
k8sServicePort: "6443"
kubeProxyReplacement: true

 # Talos specific
#k8sServiceHost: localhost
#k8sServicePort: 7445
securityContext:
  capabilities:
    ciliumAgent: [ CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID ]
    cleanCiliumState: [ NET_ADMIN,SYS_ADMIN,SYS_RESOURCE ]

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

# https://docs.cilium.io/en/stable/network/concepts/ipam/
ipam:
  mode: kubernetes

operator:
  #  # Can't have more replicas than nodes
  replicas: 2
  rollOutPods: true
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

#debug:
#  enabled: true

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 20
  burst: 100

l2announcements:
  enabled: true

externalIPs:
  enabled: true

enableCiliumEndpointSlice: true

gatewayAPI:
  enabled: true

hubble:
  enabled: false
  relay:
    enabled: false
    rollOutPods: true
  ui:
    enabled: false
    rollOutPods: true

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  service:
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.223
    # Random values so Argo CD doesn't complain about the service being out of sync
    insecureNodePort: 32434
    secureNodePort: 31247
