apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
  namespace: haos
spec:
  parentRefs:
    - name: stonegarden
      namespace: gateway
  hostnames:
    - "haos.vanillax.xyz"
  rules:
    - backendRefs:
        - name: home-assistant
          port: 8123