apiVersion: v1
kind: Namespace
metadata:
  name: 1passwordconnect
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: 1passwordconnect
  namespace: 1passwordconnect
spec:
  data:
  - remoteRef:
      key: 1passwordconnect
      property: 1password-credentials.json
    secretKey: json
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        1password-credentials.json: '{{ .json | b64enc }}'
