apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mitchross/k3s-argocd-raspberrypi
        revision: HEAD
        directories:
          - path: infra/core/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        dev.stonegarden: core
    spec:
      project: core
      source:
        plugin:
          name: argocd-vault-plugin-kustomize-build-with-helm
        repoURL: https://github.com/mitchross/k3s-argocd-raspberrypi
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true