apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1passwordconnect
  namespace: argocd
spec:
  destination:
    namespace: 1passwordconnect
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: connect
    helm:
      valueFiles:
      - ../../manifests/applications/1passwordconnect/values.yaml
    repoURL: https://1password.github.io/connect-helm-charts
    targetRevision: 1.15.0
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
