apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: core
    jsonPointers:
    - /data/ca.crt
    kind: ConfigMap
    name: hubble-ca-cert
  - group: core
    jsonPointers:
    - /data/ca.crt
    - /data/tls.crt
    - /data/tls.key
    kind: Secret
    name: hubble-relay-client-certs
  - group: core
    jsonPointers:
    - /data/ca.crt
    - /data/tls.crt
    - /data/tls.key
    kind: Secret
    name: hubble-server-certs
  - group: core
    jsonPointers:
    - /data/ca.crt
    - /data/ca.key
    kind: Secret
    name: cilium-ca
  project: homelab
  source:
    chart: cilium
    helm:
      valueFiles:
      - ../../manifests/applications/cilium/values.yaml
    repoURL: https://helm.cilium.io/
    targetRevision: 1.16.0-pre.2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
