apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: coredns
    helm:
      valueFiles:
      - ../../manifests/applications/coredns/values.yaml
    repoURL: https://coredns.github.io/helm
    targetRevision: 1.31.0
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
