apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: external-dns
    helm:
      valueFiles:
      - ../../manifests/operators/external-dns/values.yaml
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.5
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
