apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatewaycrds
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    path: .
    plugin:
      env:
      - name: KUSTOMIZATION_YAML
        value: "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\n\
          resources:\n  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml\n\
          \  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml\n\
          \  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml\n\
          \  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/experimental/gateway.networking.k8s.io_gateways.yaml\n\
          \  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml\n\
          \  - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.0.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml\n"
      name: kustomize-inline
    repoURL: https://github.com/acelinkio/empty.git
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
