apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: grafana
    helm:
      valueFiles:
      - ../../manifests/applications/grafana/values.yaml
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.0.2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
