apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  destination:
    namespace: test-zone
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: app-template
    helm:
      valueFiles:
      - ../../manifests/applications/homepage/values.yaml
    repoURL: http://bjw-s.github.io/helm-charts/
    targetRevision: 1.5.1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
