apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: loki
    helm:
      valueFiles:
      - ../../manifests/applications/loki/values.yaml
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.6.5
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
