apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-system
  namespace: argocd
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: longhorn
    helm:
      valueFiles:
      - ../../manifests/infrastructure/longhorn-system/values.yaml
    repoURL: https://charts.longhorn.io
    targetRevision: 1.6.2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
