apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: metrics-server
    helm:
      valueFiles:
      - ../../manifests/applications/metrics-server/values.yaml
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.12.1
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
