apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: postgres-operator
    helm:
      valueFiles:
      - ../../manifests/operators/postgres-operator/values.yaml
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    targetRevision: 1.12.2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
