apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-operator
  namespace: argocd
spec:
  destination:
    namespace: rabbitmq-operator
    server: https://kubernetes.default.svc
  project: homelab
  source:
    chart: bitnamicharts/rabbitmq-cluster-operator
    helm:
      valueFiles:
      - ../../manifests/applications/rabbitmq-cluster-operator/values.yaml
    repoURL: registry-1.docker.io
    targetRevision: 4.3.11
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
