apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/mitchross/k3s-argocd-raspberrypi'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'pve-csi'
      server: '*'
    - namespace: 'whoami'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
