apiVersion: v1
kind: Namespace
metadata:
  name: test-zone
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: test-zone
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: httpbin
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: test-zone
spec:
  hostnames:
  - httpbin.<path:stringreplacesecret#domain>
  parentRefs:
  - name: internal
    namespace: gateway
    sectionName: https
  rules:
  - backendRefs:
    - name: httpbin
      port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  annotations:
    external-dns.custom/type: private
  name: httpbin
  namespace: test-zone
spec:
  endpoints:
  - dnsName: httpbin.<path:stringreplacesecret#domain>
    providerSpecific:
    - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
      value: 'false'
    recordType: CNAME
    targets:
    - intgw.<path:stringreplacesecret#domain>
