apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: proxmox-csi
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 700Mi
  accessModes:
    - ReadWriteOnce
  iscsi:
    iqn:
    lun:
    targetPortal: