apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external
  namespace: argocd
spec:
  sourceRepos:
    - 'https://gitlab.com/vehagn/mini-homelab.git'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'home-assistant'
      server: '*'
    - namespace: 'proxmox'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
