apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-structure
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: infrastructure
      - name: operators
      - name: applications
  template:
    metadata:
      name: '{{.name}}'
    spec:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      project: homelab
      source:
        path: manifests/{{.name}}
        repoURL: https://github.com/mitchross/k8s-homelab-argocd.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
