---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBvHFOkLJ+Jle3VqJQMM6qkN9Siv8z6wUK5gWNMTY1KpIEEwKhJuXRW4+J8jveYoJEjNU+sYqk1TfTva+sBFpUGeEfADh2X8VANUQOUC9nQ3IK7L/DqoafqyLWpLpidP0EpLwfkZTquQYq9yM9LyROuZvmfY4Is8LaKE5qYMSLmLsPBAkf07LtaqMTHRl8wp3fvulLdfE15IfQfkDpZi6K5YcO+8KYbaKi8h69egqDPLg7HIgU/D25BnI6HuXOyx4wnWAod4NCqeeITSEGMHufC86st/foc9kPKm9Pc+TtqpUazZ6VF1/sph+hhCuz3gWJ8fDr+QtDGPnjulUtoqbH2tyUTzxcCTflFtWrZbBj6LFfktLRURlLxq2nsnPSQ7fhkqaIcUbAvwh8OjLSNaZtmtTa7uMwqNdySCUFfs4YlacqktdWfM4h+iaKWbqu2QM1d5wth1Kfl4u2bSYIuANBxrPCPtnBe0ZsKQZgrMbiX44ODsCLDgAE9KRD9dahuGtIFq2AKI3lLY5XpDRBuN75gePWaOtAorSBKL/oj/H1yQgfigJTs/nI2L6tjnkgfaKu9oRXQQlpGzaR4dvL8of1MwXcR4sySnWNEF1JvfqGINqnGQq3ad0W/Q7QEvpZIxB5YAcgwVCi5o5D9RrAg2W8jWXgXsVKgeZp8CN9gvzr3szEL/xsU/uuCDtkN20OeeE6IiBJ3icJy/Z+dBC3ws335XNLspEspPAD6zewXnAf2mmDsyY2csEwA
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
