---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBoNhJZs7JT145KNMS55mQPjQ9EOjzLHdffCeueirpuvLU7Ck325dT26ZrQKs2QICi/4PHB5lPpLOkO5t74+NKrxr5xXUjXd0AJnvCUYpnMazbBuoqRmm2s/d451B8pAVC8RzLMlnPVurnFVd38RPGwmFSv4PUyiHTVb52TEdoybaSRLYTE/vMh68PfxAbGl7UGWWS7VljH+Y3MbaElyO7wUer+Zg3rNChTWg5vDzXzY8MtOVShWmcT4MS012lusA5qT9W5a8lptVTivB26rADmtZHjPaoxH8rKNgSb6Mwxh1FObsDnk804ZvMPLufmJDZ78EBPYiVqD9YnzQMwgXFrzokitUuESg6Vohk9Z308ABpfG9bOvw7xmKPL2qSZTJ+zxnuQCX/UOB3qRS4ny+YuC82JypKiOfYUrx0Bf0jbZ2hOuYlYbwTjQSkufuS2y2XGJxEiC/MIyjgIuCc2pMf4x9PqapmGfNnKkyzw2oXGw0Q9uOMWaA2GMCvUyD3out5R5jgVctWRh+qf6LkWZBqdWJI6WqNwoxsmwV2UCGeIAFmY5Rw+jcBk6bkQDNtVBAiGGt5D/A+nnpJcRt5tDRaACUOitvO46xyQH/TS8l/8FPPSkh2e/eQ4bZYzvtfM44tDd6VtqvKO+lNNa7zv4RsnhUWzmIQrXkf8d5tQWvuuhPMpZ8wSN+ORmRcHOtSSIRwWg3s5Eu3I0bheUKxRUapJ6YV6QHuridLbLCQQTZiep1NQBS1nKDxw
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
