apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.14.2
    releaseName: sealed-secrets-controller
    namespace: sealed-secrets
    includeCRDs: true
    valuesFile: values.yaml
