grafana:
  enabled: false
kubeApiServer:
  enabled: true
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubelet:
  enabled: false
prometheus:
  prometheusSpec:
    retention: 1d
